### ISSUE TITLE
Include standard deviation or other measure of spread

### ISSUE THREAD

**Issue by rtoy** [spotify/web-audio-bench#3]
Since the benchmark appears to run each test multiple times, it would be useful if the output included the standard deviation (or something) so we can get a feel for how much variation there is in running the test.

Pretty low priority.

**Comment by bjornm** [comment]
Good suggestion! How about box plots? https://plot.ly/javascript/box-plots/

**Comment by rtoy** [comment]
I'd be just as happy if you just made the current output like
```
Test  value +/- stddev
```
but pretty plots are pretty. 

As long as you include the raw data too so it's easier to compare the results between two browser runs or so I can just copy out the raw data.

**Comment by bjornm** [comment]
Since distribution will most likely be skewed (extreme outliers to the right for very slow runs), I think stddev will not be representative enough. Instead I added min, q1, median, q3 and max values, which is what show in a box plot.

See https://en.wikipedia.org/wiki/Five-number_summary

Please try it out and tell me what you think. My thought is that you want to make sure that the quartiles are fairly close to the median.

If you want to, I can of course also add stddev as a column, it's not hard to calculate.

**Comment by rtoy** [comment]
The 5-number summary is fine.  As long as I can cut and paste the numbers. :-)

Really appreciate your work on this!

**Comment by bjornm** [comment]
Thanks!
